//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/InputSystem/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""13fc5ee3-f907-45e0-af8e-387f07b6e206"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""2bee663b-ee33-4f68-91c9-fc7a85d4098b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FireShoot"",
                    ""type"": ""Button"",
                    ""id"": ""fa590118-89f3-455c-aa39-5f5623cd88a0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IceShoot"",
                    ""type"": ""Button"",
                    ""id"": ""5b221e18-a1c5-4de2-b6b2-36198265b257"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseSlot1"",
                    ""type"": ""Button"",
                    ""id"": ""6e6a7a1c-2735-468a-b63b-21428f911183"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseSlot2"",
                    ""type"": ""Button"",
                    ""id"": ""eeacbc9e-0b33-4980-8130-aee930e75337"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseSlot3"",
                    ""type"": ""Button"",
                    ""id"": ""392bbd74-8624-4a3e-9dc9-59821d230c9f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""192e3ea3-721c-4ccb-8555-81ad69d986af"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9fa00c9-f158-4b21-91ad-e9cec02e246d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FireShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cfd85899-937e-4fc0-a0c7-5e84b654e67f"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IceShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea5fbf21-12ec-46dc-84c3-e8760d3430fb"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseSlot1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8344467-0550-4206-9fa0-05a89bf72c46"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseSlot2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""535c02e6-70de-41b3-b16a-752ff2ae164b"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseSlot3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_FireShoot = m_Player.FindAction("FireShoot", throwIfNotFound: true);
        m_Player_IceShoot = m_Player.FindAction("IceShoot", throwIfNotFound: true);
        m_Player_UseSlot1 = m_Player.FindAction("UseSlot1", throwIfNotFound: true);
        m_Player_UseSlot2 = m_Player.FindAction("UseSlot2", throwIfNotFound: true);
        m_Player_UseSlot3 = m_Player.FindAction("UseSlot3", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_FireShoot;
    private readonly InputAction m_Player_IceShoot;
    private readonly InputAction m_Player_UseSlot1;
    private readonly InputAction m_Player_UseSlot2;
    private readonly InputAction m_Player_UseSlot3;
    public struct PlayerActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @FireShoot => m_Wrapper.m_Player_FireShoot;
        public InputAction @IceShoot => m_Wrapper.m_Player_IceShoot;
        public InputAction @UseSlot1 => m_Wrapper.m_Player_UseSlot1;
        public InputAction @UseSlot2 => m_Wrapper.m_Player_UseSlot2;
        public InputAction @UseSlot3 => m_Wrapper.m_Player_UseSlot3;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Jump.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @FireShoot.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFireShoot;
                @FireShoot.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFireShoot;
                @FireShoot.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFireShoot;
                @IceShoot.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnIceShoot;
                @IceShoot.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnIceShoot;
                @IceShoot.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnIceShoot;
                @UseSlot1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUseSlot1;
                @UseSlot1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUseSlot1;
                @UseSlot1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUseSlot1;
                @UseSlot2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUseSlot2;
                @UseSlot2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUseSlot2;
                @UseSlot2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUseSlot2;
                @UseSlot3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUseSlot3;
                @UseSlot3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUseSlot3;
                @UseSlot3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUseSlot3;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @FireShoot.started += instance.OnFireShoot;
                @FireShoot.performed += instance.OnFireShoot;
                @FireShoot.canceled += instance.OnFireShoot;
                @IceShoot.started += instance.OnIceShoot;
                @IceShoot.performed += instance.OnIceShoot;
                @IceShoot.canceled += instance.OnIceShoot;
                @UseSlot1.started += instance.OnUseSlot1;
                @UseSlot1.performed += instance.OnUseSlot1;
                @UseSlot1.canceled += instance.OnUseSlot1;
                @UseSlot2.started += instance.OnUseSlot2;
                @UseSlot2.performed += instance.OnUseSlot2;
                @UseSlot2.canceled += instance.OnUseSlot2;
                @UseSlot3.started += instance.OnUseSlot3;
                @UseSlot3.performed += instance.OnUseSlot3;
                @UseSlot3.canceled += instance.OnUseSlot3;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnFireShoot(InputAction.CallbackContext context);
        void OnIceShoot(InputAction.CallbackContext context);
        void OnUseSlot1(InputAction.CallbackContext context);
        void OnUseSlot2(InputAction.CallbackContext context);
        void OnUseSlot3(InputAction.CallbackContext context);
    }
}
